image: jakzal/phpqa

before_script:
  - composer install

cache:
  paths:
    - vendor/

stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

security-checker:
  stage: SecurityChecker
  script:
    - security-checker security:check composer.lock
  allow_faillure: false

phpcs:
  stage: CodingStandards
  script:
    - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
  allow_faillure: false

phpstan:
  stage: CodingStandards
  script:
    - phpstan analyst ./src
  allow_faillure: false 

twig-lint:
  stage: CodingStandards
  script:
    - twig-lint lint ./templates
  allow_faillure: false

  phpunit:
    stage: UnitTests
    script:
      - php bin/phpunit
    allow_faillure: false